BT: null
BTObj: null
activation_function: Tanh
adv_BT: null
adv_BTObj: null
adv_activation_function: ReLu
adv_batch_norm: false
adv_batch_size: 1024
adv_checkpoint_interval: 1
adv_debiasing: true
adv_decoupling: false
adv_diverse_lambda: 0.1
adv_dropout: 0
adv_epochs: 100
adv_epochs_since_improvement: 5
adv_gated: true
adv_gated_mapping: null
adv_hidden_size: 300
adv_lambda: 19.952623149688787
adv_level: last_hidden
adv_lr: 0.001
adv_n_hidden: 2
adv_num_classes: 2
adv_num_subDiscriminator: 3
adv_test_batch_size: 1024
adv_uniform_label: false
adv_update_frequency: Batch
base_seed: 2013
batch_norm: false
batch_size: 1024
checkpoint_interval: 1
data_dir: null
dataset: Moji
device_id: 0
dropout: 0.0
emb_size: 2304
encoder_architecture: Fixed
epochs: 100
epochs_since_improvement: 10
exp_id: hypertune_GDAdv_1_19.952623149688787_3_0.1_2013
full_label: true
gated: false
gated_mapping: null
hidden_size: 300
log_file: ./results/hypertune3/Moji/hypertune_GDAdv_1_19.952623149688787_3_0.1_2013/output.log
log_interval: 50
log_level: INFO
lr: 0.003
model_dir: ./results/hypertune3/Moji/hypertune_GDAdv_1_19.952623149688787_3_0.1_2013/models
n_hidden: 2
no_log: false
num_classes: 2
num_workers: 0
project_dir: hypertune3
results_dir: ./results/
start_time: '2022-03-03 17:15:56'
test_batch_size: 1024
