BT: null
BTObj: null
activation_function: Tanh
adv_BT: Reweighting
adv_BTObj: stratified_g
adv_activation_function: ReLu
adv_batch_norm: false
adv_batch_size: 1024
adv_checkpoint_interval: 1
adv_debiasing: true
adv_decoupling: false
adv_diverse_lambda: 0.0
adv_dropout: 0
adv_epochs: 100
adv_epochs_since_improvement: 5
adv_gated: true
adv_gated_mapping: null
adv_hidden_size: 300
adv_lambda: 0.3981071705534973
adv_level: last_hidden
adv_lr: 0.001
adv_n_hidden: 2
adv_num_classes: 2
adv_num_subDiscriminator: 1
adv_test_batch_size: 1024
adv_uniform_label: false
adv_update_frequency: Batch
base_seed: 9254525
batch_norm: false
batch_size: 1024
checkpoint_interval: 1
data_dir: null
dataset: Bios_gender
device_id: 0
dropout: 0.0
emb_size: 768
encoder_architecture: Fixed
epochs: 20
epochs_since_improvement: 10
exp_id: BTGAdv_hypertune_0.3981071705534973_1_0_3
full_label: true
gated: false
gated_mapping: null
hidden_size: 300
log_file: ./results/hypertune4/Bios_gender/BTGAdv_hypertune_0.3981071705534973_1_0_3/output.log
log_interval: 50
log_level: INFO
lr: 0.003
model_dir: ./results/hypertune4/Bios_gender/BTGAdv_hypertune_0.3981071705534973_1_0_3/models
n_hidden: 2
no_log: false
num_classes: 28
num_workers: 0
project_dir: hypertune4
results_dir: ./results/
start_time: '2022-03-05 06:22:41'
test_batch_size: 1024
