BT: null
BTObj: null
DyBT: GroupDifference
DyBTObj: EO
DyBTalpha: 0.31622776601683794
DyBTinit: original
FCL: false
INLP: false
INLP_by_class: false
INLP_discriminator_reweighting: null
INLP_min_acc: 0.0
INLP_n: 300
activation_function: Tanh
adv_BT: null
adv_BTObj: null
adv_activation_function: ReLu
adv_batch_norm: false
adv_batch_size: 1024
adv_checkpoint_interval: 1
adv_debiasing: false
adv_decoupling: false
adv_diverse_lambda: 0.0
adv_dropout: 0
adv_epochs: 100
adv_epochs_since_improvement: 5
adv_gated: false
adv_gated_mapping: null
adv_hidden_size: 300
adv_lambda: 1
adv_level: last_hidden
adv_lr: 0.001
adv_n_hidden: 2
adv_num_subDiscriminator: 1
adv_test_batch_size: 1024
adv_uniform_label: false
adv_update_frequency: Batch
base_seed: 9862397
batch_norm: false
batch_size: 1024
checkpoint_interval: 1
data_dir: null
dataset: Moji
device_id: 0
dropout: 0.0
emb_size: 2304
encoder_architecture: Fixed
epochs: 100
epochs_since_improvement: 10
exp_id: GDEO_EO_0.31622776601683794_1
fcl_base_temperature_g: 0.01
fcl_base_temperature_y: 0.01
fcl_lambda_g: 0.1
fcl_lambda_y: 0.1
fcl_temperature_g: 0.01
fcl_temperature_y: 0.01
full_label: true
gated: false
gated_mapping: null
hidden_size: 300
log_file: /data/cephfs/punim0478/xudongh1/experimental_results/Fair_NLP_Classification/GroupDifference/Moji/GDEO_EO_0.31622776601683794_1/output.log
log_interval: 50
log_level: INFO
lr: 0.003
model_dir: /data/cephfs/punim0478/xudongh1/experimental_results/Fair_NLP_Classification/GroupDifference/Moji/GDEO_EO_0.31622776601683794_1/models
n_hidden: 2
no_log: false
num_classes: 2
num_groups: 2
num_workers: 0
project_dir: GroupDifference
results_dir: /data/cephfs/punim0478/xudongh1/experimental_results/Fair_NLP_Classification
start_time: '2022-03-15 01:52:04'
test_batch_size: 1024
