BT: null
BTObj: null
DyBT: FairBatch
DyBTObj: stratified_y
DyBTalpha: 0.05011872336272725
DyBTinit: original
INLP: false
INLP_by_class: false
INLP_discriminator_reweighting: null
INLP_min_acc: 0.0
INLP_n: 300
activation_function: Tanh
adv_BT: null
adv_BTObj: null
adv_activation_function: ReLu
adv_batch_norm: false
adv_batch_size: 1024
adv_checkpoint_interval: 1
adv_debiasing: false
adv_decoupling: false
adv_diverse_lambda: 0.0
adv_dropout: 0
adv_epochs: 100
adv_epochs_since_improvement: 5
adv_gated: false
adv_gated_mapping: null
adv_hidden_size: 300
adv_lambda: 1
adv_level: last_hidden
adv_lr: 0.001
adv_n_hidden: 2
adv_num_classes: 2
adv_num_subDiscriminator: 1
adv_test_batch_size: 1024
adv_uniform_label: false
adv_update_frequency: Batch
base_seed: 1141410
batch_norm: false
batch_size: 1024
checkpoint_interval: 1
data_dir: null
dataset: Bios_gender
device_id: 0
dropout: 0.0
emb_size: 768
encoder_architecture: Fixed
epochs: 100
epochs_since_improvement: 10
exp_id: Original_FairBatch_stratified_y_0.05011872336272725_original_1
full_label: true
gated: false
gated_mapping: null
hidden_size: 300
log_file: /data/cephfs/punim0478/xudongh1/experimental_results/Fair_NLP_Classification/hypertune8/Bios_gender/Original_FairBatch_stratified_y_0.05011872336272725_original_1/output.log
log_interval: 50
log_level: INFO
lr: 0.003
model_dir: /data/cephfs/punim0478/xudongh1/experimental_results/Fair_NLP_Classification/hypertune8/Bios_gender/Original_FairBatch_stratified_y_0.05011872336272725_original_1/models
n_hidden: 2
no_log: false
num_classes: 28
num_workers: 0
project_dir: hypertune8
results_dir: /data/cephfs/punim0478/xudongh1/experimental_results/Fair_NLP_Classification
start_time: '2022-03-10 02:20:35'
test_batch_size: 1024
